name: HTMLCheck
on: 
  push:
    branches: [main]
 
jobs:
  TestHtml:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Check HTML Syntax
        run: npx pretter *.html
 

  
  
  
